architect:
  - amihaiemil
docker:
  as_root: true
install: |-
  sudo apt-get update
  sudo apt-get install nodejs
  sudo apt-get install npm
  sudo npm install
  ./node_modules/.bin/webpack --version
decrypt:
  deployment.txt: "repo/dcfg/deployment.txt.asc"
merge:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
deploy:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
    curl -H "Authorization: token test" -X PUT -d '{"message": "my commit message", "content": "bXkgbmV3IGZpbGUgY29udGVudHM="}' https://api.github.com/repos/amihaiemil/amihaiemil.github.io/contents/js/test.js
    //...curl to post js and css files to amihaiemil.github.io
release:
  script:
  - echo "Any release script here..."
