architect:
  - amihaiemil
docker:
  as_root: true
install: |-
  sudo apt-get update
  sudo apt-get install nodejs
  sudo apt-get install npm
  sudo npm install
  ./node_modules/.bin/webpack --version
merge:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
deploy:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
    //...curl to post js and css files to amihaiemil.github.io
release:
  script:
  - echo "Any release script here..."
