architect:
  - amihaiemil
docker:
  as_root: true
install: |-
  #curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  #sudo apt-get install -y nodejs
  sudo apt-get update
  sudo apt-get install nodejs
  sudo apt-get install npm
  sudo npm install
  ./node_modules/.bin/webpack --version
merge:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
deploy:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
    pwd
    ls
    cd ..
    git clone git@github.com:amihaiemil/amihaiemil.github.io.git > /dev/null << EOF
    yes
    EOF
release:
  script:
  - echo "Any release script here..."
