architect:
  - amihaiemil
docker:
  as_root: true
install: |-
  sudo apt-get update
  sudo apt-get install nodejs
  sudo apt-get install npm
  sudo apt-get install jq
  sudo npm install
  ./node_modules/.bin/webpack --version
decrypt:
  deployment.txt: "repo/dcfg/deployment.txt.asc"
merge:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
deploy:
  script: |-
    NODE_ENV=production ./node_modules/.bin/webpack
    chmod +x ./rrv.sh
    ./rrv.sh
release:
  script:
  - echo "Any release script here..."
